"""Initial migration with performance indexes

Revision ID: b03f8e90c59a
Revises: 
Create Date: 2026-04-05 00:26:07.005216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03f8e90c59a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_detections_camera_id'), 'detections', ['camera_id'], unique=False)
    op.create_index(op.f('ix_detections_latitude'), 'detections', ['latitude'], unique=False)
    op.create_index(op.f('ix_detections_longitude'), 'detections', ['longitude'], unique=False)
    op.create_index(op.f('ix_edge_metrics_device_id'), 'edge_metrics', ['device_id'], unique=False)
    op.create_index(op.f('ix_edge_metrics_timestamp'), 'edge_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_reports_priority_level'), 'reports', ['priority_level'], unique=False)
    op.create_index(op.f('ix_reports_problem_type'), 'reports', ['problem_type'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_timestamp'), 'reports', ['timestamp'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_reports_timestamp'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_problem_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_priority_level'), table_name='reports')
    op.drop_index(op.f('ix_edge_metrics_timestamp'), table_name='edge_metrics')
    op.drop_index(op.f('ix_edge_metrics_device_id'), table_name='edge_metrics')
    op.drop_index(op.f('ix_detections_longitude'), table_name='detections')
    op.drop_index(op.f('ix_detections_latitude'), table_name='detections')
    op.drop_index(op.f('ix_detections_camera_id'), table_name='detections')
    # ### end Alembic commands ###
