"""Add missing user columns

Revision ID: f6046aa25ffa
Revises: 12df218c5371
Create Date: 2026-04-21 00:40:07.651212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f6046aa25ffa'
down_revision: Union[str, None] = '12df218c5371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('table_name', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.alter_column('detections', 'latitude',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('detections', 'longitude',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('detections', 'confidence',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('detections', 'object_type',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('detections', 'camera_id',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('detections', 'image_path',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('ix_detections_latitude', table_name='detections')
    op.drop_index('ix_detections_longitude', table_name='detections')
    op.create_index('idx_user_created', 'detections', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_detections_user_id'), 'detections', ['user_id'], unique=False)
    op.create_foreign_key(None, 'detections', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('detections', 'label')
    op.add_column('edge_metrics', sa.Column('cpu_usage', sa.Float(), nullable=True))
    op.add_column('edge_metrics', sa.Column('memory_usage', sa.Float(), nullable=True))
    op.add_column('edge_metrics', sa.Column('bandwidth_saved_mb', sa.Float(), nullable=True))
    op.add_column('edge_metrics', sa.Column('privacy_compliance_score', sa.Float(), nullable=True))
    op.alter_column('edge_metrics', 'device_id',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_edge_metrics_id'), 'edge_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_edge_metrics_user_id'), 'edge_metrics', ['user_id'], unique=False)
    op.create_foreign_key(None, 'edge_metrics', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('edge_metrics', 'inference_ms')
    op.drop_column('edge_metrics', 'bandwidth_saved_kb')
    op.add_column('reports', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('reports', 'problem_type',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('reports', 'location',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('reports', 'image_path',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('reports', 'status',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('reports', 'priority_level',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_index('ix_reports_priority_level', table_name='reports')
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index('ix_users_created_at', table_name='users')
    op.alter_column('work_orders', 'detection_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('work_orders', 'status',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('work_orders', 'priority',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_work_orders_assigned_user_id'), 'work_orders', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_work_orders_detection_id'), 'work_orders', ['detection_id'], unique=False)
    op.drop_constraint('work_orders_ibfk_2', 'work_orders', type_='foreignkey')
    op.create_foreign_key(None, 'work_orders', 'detections', ['detection_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.create_foreign_key('work_orders_ibfk_2', 'work_orders', 'detections', ['detection_id'], ['id'])
    op.drop_index(op.f('ix_work_orders_detection_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_assigned_user_id'), table_name='work_orders')
    op.alter_column('work_orders', 'priority',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('work_orders', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('work_orders', 'detection_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=128),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.create_index('ix_reports_priority_level', 'reports', ['priority_level'], unique=False)
    op.alter_column('reports', 'priority_level',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('reports', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('reports', 'image_path',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('reports', 'location',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('reports', 'problem_type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    op.drop_column('reports', 'updated_at')
    op.add_column('edge_metrics', sa.Column('bandwidth_saved_kb', mysql.FLOAT(), nullable=True))
    op.add_column('edge_metrics', sa.Column('inference_ms', mysql.FLOAT(), nullable=True))
    op.drop_constraint(None, 'edge_metrics', type_='foreignkey')
    op.drop_index(op.f('ix_edge_metrics_user_id'), table_name='edge_metrics')
    op.drop_index(op.f('ix_edge_metrics_id'), table_name='edge_metrics')
    op.alter_column('edge_metrics', 'device_id',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.drop_column('edge_metrics', 'privacy_compliance_score')
    op.drop_column('edge_metrics', 'bandwidth_saved_mb')
    op.drop_column('edge_metrics', 'memory_usage')
    op.drop_column('edge_metrics', 'cpu_usage')
    op.add_column('detections', sa.Column('label', mysql.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'detections', type_='foreignkey')
    op.drop_index(op.f('ix_detections_user_id'), table_name='detections')
    op.drop_index('idx_user_created', table_name='detections')
    op.create_index('ix_detections_longitude', 'detections', ['longitude'], unique=False)
    op.create_index('ix_detections_latitude', 'detections', ['latitude'], unique=False)
    op.alter_column('detections', 'image_path',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('detections', 'camera_id',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('detections', 'object_type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('detections', 'confidence',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('detections', 'longitude',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('detections', 'latitude',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
